version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Build started
      - chmod +x scripts/start_server.sh
      - chmod +x scripts/stop_server.sh

artifacts:
  files:
    - app.js
    - package.json
    - package-lock.json
    - appspec.yml
    - scripts/**/*
